### PR TITLE
Add FCO to the list

### PR DESCRIPTION
**Pull request by AlexDaniel**
This is a resubmission of https://github.com/perl6/problem-solving/pull/82 originally submitted by @FCO. The previous PR was merged ahead of time before everyone had a chance to accept it, so this PR resubmits the same change.

Ping @JJ @jnthn @lizmat @maettu @masak @MasterDuke17 @moritz @rba @samcv @timo @tony-o @ugexe.

### CODE REVIEW

**Comment by AlexDaniel** [comment]
To prevent this from happening again, I bumped the amount of required reviews in github settings. Reason why it wasn't done before? Github doesn't have a drop down option for reviewer counts beyond 6. I had to edit and resend the web request with a bigger number, and I'm very pleased they don't limit it on the server side :)

**Comment by FCO** [comment]
What happens if it becomes stuck?

**Comment by moritz** [comment]
@FCO admins can still merge without the required number of reviews.

**Comment by AlexDaniel** [comment]
> @FCO admins can still merge without the required number of reviews.

Not exactly.

In case someone doesn't leave a review, there's a deadline:

> If a reviewer does not respond in 14 days, they are removed from the list of reviewers on that PR.

So it can only become stuck if there's a disagreement. The assumption is that grown ups will always come to an agreement, and if they really don't, maybe the change is not worth doing after all.

See https://github.com/perl6/problem-solving#acceptance.

**Comment by tony-o** [comment]
It's my opinion these should wait until after the great renaming debate is, once again, resolved.

**Comment by AlexDaniel** [comment]
@tony-o well, I guess the concern is that people might start flocking into the list to cause trouble with the naming solution? I think that is possible in the future, but I feel pretty safe regarding the PRs that we have right now.

**Comment by tony-o** [comment]
@AlexDaniel not sure it's good precedence to set, allowing a shuffling of approvers/rejectors prior to major language changes, is more the concern.

**Comment by AlexDaniel** [comment]
@tony-o I agree, but at the same time I think some devs didn't really get a good chance to add themselves because the problem-solving repo didn't have many tickets that actually required consensus. I don't want anyone to feel left out.

**Comment by tony-o** [comment]
@AlexDaniel while I dislike people feeling left out making an exception on handling one of the first major issues we're facing as a community _sets_ the precedent and reversing that will be difficult, the context will also be lost (as is it is with the renaming issue).

If it causes feelings of bitterness or resentment then the people waiting to be added might not be a good fit for making decisions in a committee, akin to the `if we change the name from perl6 then I'll just stop participating in the language`.

**Comment by vrurg** [comment]
As a candidate, I would support @tony-o. Let the dust settle down first.

**Comment by AlexDaniel** [comment]
OK, no problem, I'll make sure not to merge this before we figure out the naming. Thank you, @tony-o and @FCO. I guess same goes for https://github.com/perl6/problem-solving/pull/83. Also, https://github.com/perl6/problem-solving/pull/87 is not even in the review stage yet, but given that it touches the `language` label, I think it'll need to wait too.

**Comment by FCO** [comment]
Is that ok to continue with this now?

**Comment by AlexDaniel** [comment]
Given that the Raku PR is now merged, I think it's safe to move on with this now. @maettu, @tony-o please leave a review :)

**Comment by AlexDaniel** [comment]
Two days left, ping @maettu, @tony-o :)

**Comment by AlexDaniel** [comment]
Sorry for the delay!

**Comment by AlexDaniel** [comment]
Also, welcome! :)

**Pull request merged**
