### PR TITLE
Adding kawaii to the reviewers list

### PR DESCRIPTION
**Pull request by kawaii**
As the title says really.

### CODE REVIEW

**Comment by AlexDaniel** [comment]
kawaii is working on rakudo releases and will hopefully replace me in the near future, so it makes sense for them to be on the list.

As mentioned in https://github.com/perl6/problem-solving/pull/82#issuecomment-519439890, the review process is now required for changing the list.

Ping @JJ @jnthn @lizmat @maettu @masak @MasterDuke17 @moritz @rba @samcv @timo @tony-o @ugexe

**Comment by kawaii** [comment]
@AlexDaniel just thought I should bump this, you may want to re-request reviews from the remaining reviewers as some time has passed.

**Comment by AlexDaniel** [comment]
@kawaii we're blocked by this: https://github.com/perl6/problem-solving/pull/84#issuecomment-521166018

**Comment by FCO** [comment]
But couldn’t reviewer reviews and delay the merge waiting to close all polemic issues/PRs?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by AlexDaniel** [comment]
Sure, and most people did.

**Comment by FCO** [comment]
Is that ok to continue with this now?

**Comment by AlexDaniel** [comment]
Yes, sure! @maettu, @tony-o mind leaving a review now? :)

**Comment by AlexDaniel** [comment]
Two days left, ping @maettu, @tony-o! :)

**Comment by AlexDaniel** [comment]
@kawaii are you still around? Please talk to me on #perl6-dev.

**Comment by AlexDaniel** [comment]
I was unable to get consistent communication with @kawaii in the last few months. I'll give it more time but right now it's a problem because I don't want every PR to bo guaranteed to be blocked for 2 weeks.

**Comment by kawaii** [comment]
Hi! Yes I still control this account, but I've been highly inactive over the last month or two due to some ongoing personal circumstances. Please defer this issue for now. I'm not done with the Raku community but I'm not in a position to frequently contribute as of now. I will be returning in the future though. :)

**Comment by AlexDaniel** [comment]
Thank you, @kawaii!

**Pull request closed without merging**
