### PR TITLE
Add vrurg to the list

### PR DESCRIPTION
**Pull request by vrurg**
I was proposed by @AlexDaniel to become the language release manager and decided to accept the proposal. Thus, this PR.

It happened so that some of my contributions to Rakudo were requiring a new `6.e` language version. As I was the only one needing it at the time, I have implemented a number of changes to make the new version possible. Among those are revamp of NQP and Rakudo build subsystems, improvements to loading of `CORE`s, improving support of language version-dependant code, done introductionary `6.e`-related changes to roast, and some more.

### CODE REVIEW

**Comment by AlexDaniel** [comment]
Before we go with the reviews, I'd like to see some feedback from @jnthn first. For example, [here's a discussion](https://colabti.org/irclogger/irclogger_log/perl6-dev?date=2019-08-12#l116) about using the `language` label vs creating a new one. I think the PR currently makes sense, but what do you think, @jnthn?

**Comment by JJ** [comment]
This is just a reminder for the remaining reviewers to check this out.

**Comment by AlexDaniel** [comment]
I'm still waiting for a reply from @jnthn.

**Comment by FCO** [comment]
Is that ok to continue with this now?

**Comment by jnthn** [comment]
I'm fully supportive of @vrurg being on the reviewers list. I'm not so keen on the language tag being shared.

**Comment by AlexDaniel** [comment]
@jnthn alright, what about adding a different tag, like `language-release` or something?

**Comment by jnthn** [comment]
@AlexDaniel So long as we can define a clean separation of the roles. so it's obvious enough what issues go where.

**Comment by AlexDaniel** [comment]
@jnthn can you define it? I'm just seeing @vrurg eager to work on the next version release and I don't want anything making their life harder. But it is totally up to you to decide.

**Comment by AlexDaniel** [comment]
@jnthn can you define it? I'm just seeing @vrurg eager to work on the next version release and I don't want anything making their life harder. But it is totally up to you to decide.

**Comment by vrurg** [comment]
@AlexDaniel I agree to Jonathan in that I'm not ready for making decisions on language design matters. `language-release` label makes sense for the following cases:

- anything related to roast
- issues with `language` label if approved are receiving `language-release` tag for project management. Correspondingly, language release project will be created.

   As we currently don't have formal approval procedure, addition of the new tag could be considered 'accepted' status.

- possibly, matters related to language promotion.

**Comment by jnthn** [comment]
> issues with language label if approved are receiving language-release tag for project management. Correspondingly, language release project will be created.

I think some kind of staged approach like this makes sense, yes. Effectively:

* `language` is about making design decisions
* `language-release` is about making sure they have a good specification in `roast`, and - since a `roast` release is a language specification release - coordinating the language releases themselves; I agree this does have a promotional angle too. (I do wonder if the tag actually should be `roast`, though perhaps `specification` would be less cryptic).

That said, for any complex feature there will surely be an amount of iteration, but I'm sure that can be handled by filing further issues for design decisions (and, of course, just discussion on IRC or elsewhere for smaller details will do).

**Comment by vrurg** [comment]
I have resubmitted by removing myself from `language` assignment.

**Comment by AlexDaniel** [comment]
The merge conflict doesn't matter, I'll be able to merge it anyway.

Please leave your reviews!

Ping @JJ @lizmat @maettu @masak @MasterDuke17 @rba @samcv @timo @tony-o

**Comment by vrurg** [comment]
@AlexDaniel there is no more conflict. I re-commited a while ago. Old reviews were reset, obviously.

**Comment by AlexDaniel** [comment]
@vrurg “This branch has conflicts that must be resolved”

**Comment by AlexDaniel** [comment]
Sorry for the delay! Welcome :)

**Comment by vrurg** [comment]
@AlexDaniel thank you!

**Comment by tony-o** [comment]
What's the deal with 0b9098d3e6049ef6a7c80fe56d879a2754bc45bd?

**Comment by AlexDaniel** [comment]
@tony-o there was a conflict so something had to be tweaked before the merge. [Here's the diff](https://github.com/perl6/problem-solving/pull/87/commits/0b9098d3e6049ef6a7c80fe56d879a2754bc45bd) of that commit you mention where you can see what happened a bit easier. The change (with removal of ugexe) comes from [this commit](https://github.com/perl6/problem-solving/commit/3fb9e4993f080ddb4c0b23ffc1fb7ed61bc86b7f) on master. So the PR is just [this change](https://github.com/perl6/problem-solving/commit/6d0c078ea04dbd64a7e0a7c2abc22483b213839e) which everybody voted on. That is, the content of this PR was not changed, I simply had to resolve the conflict.

I guess there is a more transparent/clean way to do it, I'll think about it next time it happens. Sorry!

**Pull request merged**
