### PR TITLE
add label infrastructure including two new members rba and maettu

### PR DESCRIPTION
**Pull request by rba**
Dear perl6 community, I hope @maettu and me can help to bring some services back, which are on the recently died community server.
And we like to bring in our experience in engineering and ops area to improve the current infrastructure.

I'm a new-be in the perl6 community. So please help me to understand what's currently around and what are the needs for development and hosting infra.

Cheers,
Roman

### CODE REVIEW

**Comment by AlexDaniel** [comment]
I just have to make sure! @maettu, are you aware that you are being added as a dev responsible for infrastructure tickets?

Also, some technical matters… Because two devs are being added to the same label, can you please clarify who is going to be responsible for what? Currently subject-matter experts are assigned to all tickets, and right now I do the assigning manually. Should I be assigning one of you, or will you be handling this yourself? One thing worth thinking about is how you will handle disagreements between each other (though there's no need to explain that to us), and what kind of privileges you will or won't have.

**Comment by AlexDaniel** [comment]
@maettu, you were missing an invite to perl6 org on github. Fixed now and you can accept it here: https://github.com/perl6. This comment also applies: https://github.com/perl6/problem-solving/issues/17#issuecomment-487299593

**Comment by maettu** [comment]
@AlexDaniel thanks, I joined. @rba are in contact with each other and will post a reply to your questions.
If you can assign me tickets that I should look into, that is valuable.

**Comment by rba** [comment]
@AlexDaniel, I've quickly spoken to @maettu on the phone. We both know each other since a while and are a good team. That's the reason I've added our both names. I believe we could offer better solutions together.

About the tickets I propose to assign them just both of us and then one of use will take care of them.

For the rare case where @maettu and me are not find consensus after internal discussions, I propose you @AlexDaniel or @jnthn will have the last word. 

For the start we need help. We like to understand how the current infrastructure components are setup and why they are setup like this. So the history would be helpful. So who should we contact?

**Comment by AlexDaniel** [comment]
OK, very good!

> For the start we need help. We like to understand how the current infrastructure components are setup and why they are setup like this. So the history would be helpful. So who should we contact?

I honestly don't know. I recommend to go to #perl6-dev and start asking questions and pinging people that may be related. https://github.com/perl6/infrastructure-doc/ is all I know about, and I also host a bunch of bots on my own personal server (see https://github.com/perl6/whateverable/wiki and https://github.com/perl6/Blin). I guess figuring out what we have now and documenting it is part of the challenge :)

**Comment by AlexDaniel** [comment]
OK, I'm very satisfied with everything, so let's get to the review stage. The deadline for opposing this change is 16th of May (two weeks from now). Please hit accept if you'd like to see it merged earlier. If there are any issues that are found after it is merged, please open a new ticket.

Note that the issue described in https://github.com/perl6/user-experience/issues/33 is something that this process tries to avoid. After this is merged, @rba and @maettu will be authorized to do decisions and work related to the infrastructure. Be prepared to provide access to them so that they can do their work. If someone disagrees with what they do, please create a new ticket in this repository instead of using social media.

**Comment by maettu** [comment]
@AlexDaniel Thanks, we've been chatting already and starting to write down some notes. Will keep you posted. It is also OK for me if some core contributors would like to have a final say. (Which could be a win-win situation in that they were close to what's happening. We make less mistakes, they get what they need.)

**Comment by AlexDaniel** [comment]
> I think it would be prudent to request some minimal proof in the form of an e.g. "I'm playing around with kubernetes" or "Here are some infrastructure ideas that demonstrate some level of knowledge in this area: ..." 

I think exactly that was provided here: https://github.com/perl6/problem-solving/issues/17#issuecomment-487286532. Wouldn't be surprised if it was unnoticed because the discussion is spread across three tickets, let me know if that is not sufficient.

While your objections are right, I don't think the implied alternative is better or feasible at all. That exact approach got us where we are now. Moreover, similar lack of organization resulted in https://github.com/perl6/user-experience/issues/33. And there are other difficulties. For example, to do the required work @rba and @maettu would need access, and being listed as an infrastructure sme will make discussions about that go much faster, I'd assume. As for giving authority to newcomers, I guess the promise and the hopeful outcome is that they'd bring order to things and we will have something that is more secure in the end.

@ugexe in your opinion, what would be a better solution for https://github.com/perl6/problem-solving/issues/9? Is there any other way we can organize efforts to achieve something nice?

**Comment by AlexDaniel** [comment]
Because all reviewers approved this PR, merging it ahead of time. Thanks!

**Pull request merged**
